export enum EndpointEnum {
  ID = '/:id',
  PARAM_ID = 'id',
  MARK_ID = '/mark/:id',
  AUTH = 'auth',
  USERS = 'users',
  DOCS = '/docs',
  LOGIN = '/login',
  REGISTER = '/registration',
  REFRESH = '/refresh',
  ROLE = '/role',
  BAN = '/ban',
  VALUE = '/:value',
  PARAM_VALUE = 'value',
  CONTACTS = 'contacts',
  POSTS = 'posts',
  IMAGE = 'image',
  ROLES = 'roles',
}
